# Generated by Django 2.1.7 on 2019-04-09 00:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adventure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strenght', models.IntegerField()),
                ('agility', models.IntegerField()),
                ('intelligence', models.IntegerField()),
                ('dexterity', models.IntegerField()),
                ('wisdom', models.IntegerField()),
                ('charisma', models.IntegerField()),
                ('constitution', models.IntegerField()),
                ('perks', models.TextField()),
                ('spellbook', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('race', models.CharField(choices=[('Humano', 'Humano'), ('Anão', 'Anão'), ('Elfo', 'Elfo'), ('Draconato', 'Draconato'), ('Orc', 'Orc'), ('Drow', 'Drow'), ('Meio-Orc', 'Meio-Orc'), ('Fae', 'Fae')], default='Humano', max_length=9)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Character'),
        ),
    ]
